service: nexus-proofreading-internal-one

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  stage: ${opt:stage, 'dev'}

functions:
  main:
    handler: handler.handler
    events:
      - http:
          path: /proofreading/internal/one
          method: POST
          cors: true
